// Writes out/_headers for the static export (Cloudflare Workers Static Assets honours `_headers`
// for asset responses only; the Worker sets the same baseline on its own responses — worker/headers.ts).
// Mode-aware: preview builds are noindex; production adds HSTS and upgrade-insecure-requests.
import { existsSync, writeFileSync } from 'node:fs';

const production = process.env.CONTENT_MODE === 'production';
if (!existsSync('out')) {
  console.error('postbuild: out/ not found — run next build first');
  process.exit(1);
}

// CSP per MASTER_PROJECT_PLAN §39. 'unsafe-inline' scripts are required by Next's inline bootstrap in a
// static export (no per-request nonces); hash-based CSP is evaluated in P10. Hosts for Turnstile (P6),
// Canva (P9), Google Maps embed (P9) and optional Cloudflare Web Analytics are pre-declared.
const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://challenges.cloudflare.com https://static.cloudflareinsights.com",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self' https://cloudflareinsights.com",
  'frame-src https://challenges.cloudflare.com https://www.canva.com https://www.canva.cn https://www.google.com',
  "form-action 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  ...(production ? ['upgrade-insecure-requests'] : []),
].join('; ');

const global = [
  'X-Content-Type-Options: nosniff',
  'Referrer-Policy: strict-origin-when-cross-origin',
  'X-Frame-Options: DENY',
  'Cross-Origin-Opener-Policy: same-origin',
  'Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  `Content-Security-Policy: ${csp}`,
  // HSTS without includeSubDomains until the client's DNS/subdomains are audited (P11, plan §42.3).
  ...(production ? ['Strict-Transport-Security: max-age=31536000'] : ['X-Robots-Tag: noindex, nofollow']),
];

const rules = [
  ['/*', global],
  // Content-hashed build output → immutable.
  ['/_next/static/*', ['Cache-Control: public, max-age=31536000, immutable']],
  // Image variants and fonts are not content-hashed (names are stable) → long but not immutable.
  ['/_img/*', ['Cache-Control: public, max-age=86400, stale-while-revalidate=604800']],
  ['/images/*', ['Cache-Control: public, max-age=86400, stale-while-revalidate=604800']],
  ['/fonts/*', ['Cache-Control: public, max-age=2592000']],
];

const body = `# Generated by scripts/postbuild.mjs (${production ? 'production' : 'preview'}) — do not edit.\n` +
  rules.map(([path, hs]) => `${path}\n${hs.map((h) => `  ${h}`).join('\n')}`).join('\n') + '\n';
writeFileSync('out/_headers', body);
console.log(`postbuild: out/_headers written (${production ? 'production' : 'preview'}, ${rules.length} rules)`);
