/**
 * Security headers for responses generated by the Worker itself. Cloudflare applies `_headers`
 * only to static-asset responses, never to Worker-generated ones, so the Worker sets its own
 * (MASTER_PROJECT_PLAN §39). Static assets get the same set from out/_headers (scripts/postbuild.mjs).
 */
export interface SiteEnv {
  /** 'preview' (default, noindex) | 'production' */
  SITE_ENV?: string;
}

export const isProduction = (env: SiteEnv) => env.SITE_ENV === 'production';

export function baseSecurityHeaders(env: SiteEnv): Record<string, string> {
  const headers: Record<string, string> = {
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'X-Frame-Options': 'DENY',
    'Cross-Origin-Opener-Policy': 'same-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  };
  if (isProduction(env)) headers['Strict-Transport-Security'] = 'max-age=31536000';
  else headers['X-Robots-Tag'] = 'noindex, nofollow';
  return headers;
}

export function withHeaders(response: Response, extra: Record<string, string>): Response {
  const out = new Response(response.body, response);
  for (const [k, v] of Object.entries(extra)) out.headers.set(k, v);
  return out;
}
