import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

// Production publication gates (audit remediation, 2026-10-02). These run the real scripts, not mocks.

const run = (script: string, env: Record<string, string>) => spawnSync(process.execPath, [script], { env: { ...process.env, ...env }, encoding: 'utf8' });

describe('production deploy workflow', () => {
  const yml = readFileSync('.github/workflows/deploy-production.yml', 'utf8');
  // Each step starts with "      - " under `steps:`; keep its whole block so step-level keys can be checked.
  const steps = yml
    .slice(yml.indexOf('    steps:'))
    .split(/\n(?= {6}- )/)
    .slice(1);
  const indexOf = (cmd: string) => steps.findIndex((s) => new RegExp(`run:\\s*${cmd.replace(/[:.]/g, '\\$&')}\\s*$`, 'm').test(s));

  it('runs site:check on the production build, after the build and before the deploy', () => {
    const build = indexOf('pnpm build');
    const check = indexOf('pnpm site:check');
    const deploy = indexOf('pnpm deploy:production');
    expect(build).toBeGreaterThan(-1);
    expect(check).toBeGreaterThan(build);
    expect(deploy).toBeGreaterThan(check);
  });

  it('makes the gate blocking: no continue-on-error, no condition, no masked exit code', () => {
    const step = steps[indexOf('pnpm site:check')]!;
    expect(step).not.toMatch(/continue-on-error/);
    expect(step).not.toMatch(/^\s+if:/m);
    expect(step).not.toMatch(/\|\|\s*true|;\s*true|exit 0/);
    expect(yml).not.toMatch(/continue-on-error:\s*true/);
  });

  it('keeps the manual approval and production restrictions', () => {
    expect(yml).toMatch(/^on:\n {2}workflow_dispatch:/m);
    expect(yml).not.toMatch(/^\s+(push|pull_request|schedule):/m);
    expect(yml).toMatch(/if: github\.event\.inputs\.confirm == 'deploy'/);
    expect(yml).toMatch(/environment: production/);
    expect(yml).toMatch(/CONTENT_MODE: production/);
    expect(yml).toMatch(/permissions:\n {2}contents: read/);
    expect(JSON.parse(readFileSync('package.json', 'utf8')).scripts['site:check']).toBe('node scripts/site-check.mjs');
  });
});

describe('site:check production output gate', () => {
  const dirs: string[] = [];
  afterEach(() => dirs.splice(0).forEach((d) => rmSync(d, { recursive: true, force: true })));

  // A PNG signature plus the IHDR width/height, which is all site:check reads of a card.
  const pngHeader = (w: number, h: number) => {
    const b = Buffer.alloc(24);
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(b);
    b.writeUInt32BE(w, 16);
    b.writeUInt32BE(h, 20);
    return b;
  };
  const site = (mode: 'production' | 'preview', body: string, payload = '', card = { url: 'https://www.example.com/og/en/privacy.png', w: 1200, h: 630 }) => {
    const out = mkdtempSync(join(tmpdir(), 'site-check-'));
    dirs.push(out);
    mkdirSync(join(out, 'en'));
    mkdirSync(join(out, 'og', 'en'), { recursive: true });
    if (card.w) writeFileSync(join(out, 'og', 'en', 'privacy.png'), pngHeader(card.w, card.h));
    writeFileSync(join(out, '_headers'), `# Generated by scripts/postbuild.mjs (${mode}) — do not edit.\n`);
    writeFileSync(
      join(out, 'en', 'privacy.html'),
      `<!DOCTYPE html><html lang="en" dir="ltr"><head><title>Privacy Policy — VISION PLUS</title><meta name="description" content="Privacy."/><meta property="og:image" content="${card.url}"/></head><body><h1>Privacy Policy</h1>${body}</body></html>`,
    );
    if (payload) writeFileSync(join(out, 'en', 'privacy.txt'), payload);
    return run('scripts/site-check.mjs', { SITE_OUT: out });
  };
  const pending = JSON.parse(readFileSync('messages/en.json', 'utf8')).pending as Record<string, string>;
  const pendingAr = JSON.parse(readFileSync('messages/ar.json', 'utf8')).pending as Record<string, string>;

  it('passes a clean production page', () => {
    expect(site('production', '<p>Policy text.</p>').status).toBe(0);
  });

  it('fails when pending-client text (D-16, D-06) reaches a production page', () => {
    const r = site('production', `<p>${pending.privacy}</p>`);
    expect(r.status).toBe(1);
    expect(r.stderr).toContain('production output contains placeholder text');
    expect(site('production', `<p>${pending.companyProfile}</p>`).status).toBe(1);
    expect(site('production', `<p>${pendingAr.privacy}</p>`).status).toBe(1);
  });

  it('fails when the text is only in the RSC payload (.txt)', () => {
    expect(site('production', '<p>Policy text.</p>', `0:["$","p",null,{"children":${JSON.stringify(pending.privacy)}}]`).status).toBe(1);
  });

  it('fails when illustrative sample content reaches a production page', () => {
    expect(site('production', '<address data-sample="">Sample</address>').status).toBe(1);
  });

  it('fails when a social card is missing, the wrong size, or not an absolute https URL in production (P5A-14)', () => {
    const ok = { url: 'https://www.example.com/og/en/privacy.png', w: 1200, h: 630 };
    expect(site('production', '<p>Policy text.</p>', '', { ...ok, w: 0 }).stderr).toContain('card /og/en/privacy.png was not built');
    expect(site('production', '<p>Policy text.</p>', '', { ...ok, h: 600 }).stderr).toContain('is not 1200×630');
    const local = site('production', '<p>Policy text.</p>', '', { ...ok, url: 'http://localhost:3000/og/en/privacy.png' });
    expect(local.status).toBe(1);
    expect(local.stderr).toContain('card URL is not absolute https');
    expect(site('preview', '<p>Policy text.</p>', '', { ...ok, url: 'http://localhost:3000/og/en/privacy.png' }).status).toBe(0);
  });

  it('leaves preview builds alone (placeholders are expected there)', () => {
    expect(site('preview', `<p>${pending.privacy}</p><address data-sample="">Sample</address>`).status).toBe(0);
  });
});

describe('content:check production gate', () => {
  it('blocks publication while Privacy and Company Profile render pending-client text', () => {
    const r = run('scripts/content-check.mjs', { CONTENT_MODE: 'production' });
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(/privacy\/page\.tsx: renders pending-client placeholder text \(pending\.privacy\)/);
    expect(r.stderr).toMatch(/company-profile\/page\.tsx: renders pending-client placeholder text \(pending\.companyProfile\)/);
  });

  it('does not change preview builds', () => {
    expect(run('scripts/content-check.mjs', { CONTENT_MODE: 'preview' }).status).toBe(0);
  });
});
